version: "3.8"
services:
    bot:
        image: change-this-name:latest
        container_name: and-this-one
        stop_signal: SIGINT
        restart: unless-stopped
        volumes:
            - ".env:/app/.env"