version: "3.8"
services:
    bot:
        build:
            context: .
        container_name: tg-bot-test
        stop_signal: SIGINT
        restart: unless-stopped
        volumes:
            - ".env:/app/.env"